Feature/dairy
AegisVP/InSight-web pull request #15
Opened 2022-12-20 19:20 UTC by Vera957

temporary

2022-12-20 22:52 UTC, AegisVP requested changes

2022-12-20 22:52 UTC, AegisVP commented on src/components/Dairy/DairyForm.js
> +const ListOfProducts = (arr) => {
({arr})...  Не забувай деструктуризовувати данні із пропсів

2022-12-20 22:52 UTC, AegisVP commented on src/components/Dairy/DairyForm.js
> +            return <li>{ua}</li>
кожен елемент списку має мати key=...

2022-12-20 22:54 UTC, AegisVP commented
В тебе prettier встановлений? Форматуй свій код з ним перед збереженням.

2022-12-21 07:14 UTC, Vera957 commented on src/components/Dairy/DairyForm.js
> +            return <li>{ua}</li>
+ключ, деструктуризація, так, це отформатовано прітієром, він так форматує

2022-12-21 23:37 UTC, AegisVP approved these changes

2022-12-21 23:37 UTC, merged