Feature#header#logic
AegisVP/InSight-web pull request #30
Opened 2022-12-23 20:26 UTC by LeonidGarasko

2022-12-23 23:51 UTC, AegisVP requested changes

2022-12-23 23:51 UTC, AegisVP commented on src/components/Logo/Logo.jsx
> +import logoMobile from '../../images/logo/logoMobile.png';
Зараз завантажуються всі 6 файлів а використовується лише 1 з них. Навіщо вигадувати костилі через JS якщо є звичайний HTML та CSS, які можуть виконати ту саму роботу?
HTML: [\<img srcset="" />](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images)
CSS: [@media (min-resolution:2dppx)](https://developer.mozilla.org/en-US/docs/Web/CSS/@media)
Або, якщо хочеш через JS, нехай завантажується лише один файл (уяви на нестабільному мобільному інтернеті на старенькому андроіді завантажувати все це...)

2022-12-23 23:59 UTC, AegisVP requested changes

2022-12-23 23:59 UTC, AegisVP commented on src/components/Logo/Logo.jsx
> +  const isMobile = useMediaQuery({ query: '(max-width: 479px)' });
Мобілка від 0 до 768px, Планшет від 768px до 1280px, Десктоп 1280px та більше
  const isMobile = useMediaQuery({ query: '(max-width: 767.95px)' });
  const isTablet = useMediaQuery({ query: '(max-width: 1279.95px)' });
  const isDesktop = useMediaQuery({ query: '(min-width: 1280px)' });

2022-12-24 09:59 UTC, LeonidGarasko commented on src/components/Logo/Logo.jsx
> +import logoMobile from '../../images/logo/logoMobile.png';
це не мій файл , я його використав із минулого мейну, спробую змінити

2022-12-24 09:59 UTC, LeonidGarasko commented on src/components/Logo/Logo.jsx
> +  const isMobile = useMediaQuery({ query: '(max-width: 479px)' });
Теж саме , спробую виправити )

2022-12-25 10:46 UTC, AegisVP commented on src/components/Logo/Logo.jsx
> +import logoMobile from '../../images/logo/logoMobile.png';
ок, по network завантажується лише 1...

2022-12-25 10:53 UTC, AegisVP requested changes

2022-12-25 10:53 UTC, AegisVP commented on src/components/NavHeader/NavHeader.jsx
> +  const calculator = 'http://localhost:3000/InSight-web/calculator';
А якщо зміниться сервер? На GitHub це вже не спрацює...

2022-12-25 17:06 UTC, AegisVP commented
- на десктопі верхній padding має бути 80px від лого
- чи не мають Log-In та Registration підсвічуватись, коли на відповідній сторінці?

2022-12-25 19:34 UTC, AegisVP approved these changes

2022-12-25 19:34 UTC, AegisVP commented on src/components/NavHeader/NavHeader.styled.js
> +    padding: ${theme.mp(5, 0, 3, 0)};
В Theme буде доданий 5 індексом відступ 60px. Індекс 6 буде 80px. Тобі який саме відступ потрібен?

2022-12-25 19:47 UTC, AegisVP approved these changes

2022-12-25 19:47 UTC, merged