Diary page logic
AegisVP/InSight-web pull request #33
Opened 2022-12-24 17:11 UTC by Polosmakrr

2022-12-24 17:16 UTC, Polosmakrr commented
Повністю готова логіка по сторінці, лишилося трохи роботи над стилями

2022-12-24 21:24 UTC, Polosmakrr commented
потрібно підключити бібліотеку 

npm i lodash

2022-12-25 00:53 UTC, AegisVP requested changes

2022-12-25 00:53 UTC, AegisVP commented on src/components/Calendar/Calendar.js
> +    const dayParam = choseDate.toLocaleDateString().split('.').join('');
В мене локаль не так форматує дату. В мене взагалі замість місяця йде день, а замість дня - місяць... Тому використовуй Date.prototype.getMonth(), ...getDate() та ...getFullYear() щоб бути впевненим що все коректно розсортувалось.

2022-12-25 00:53 UTC, AegisVP commented on src/components/SideBar/SideBar.js
> +  const consumed = diet.dailyCalories - left;
переплутані місцями consumed та left

2022-12-25 00:53 UTC, AegisVP commented on src/components/SideBar/SideBar.js
> +  //---------------------------------------------------------------------
Розділи потім код (окремо функції, окремо jsx)

2022-12-25 00:53 UTC, AegisVP commented on src/components/DiaryForm/Form.js
> +          {allProducts.length !== 0 && showAutocomplete && (
Коли вводиш пошук, якого не існує в базі, AutocompleteList не очищується (лишається список попередніх продуктів). Набери "Борщ", в списку буде все на "бор" але борща там немає...

2022-12-25 00:53 UTC, AegisVP commented on src/components/DiaryForm/Form.js
> +  const params = useParams();
дата з адресної строки (з params) не обробляється і форма відкриває лише поточну дату

2022-12-25 00:53 UTC, AegisVP commented on src/components/DiryProductsList/DiryProductsList.js
> +export const DiryproductsList = ({ products, onClickItem }) => {
DiaryProductList буде правильніше

2022-12-25 00:53 UTC, AegisVP commented on src/components/DiryProductsList/DiryProductsList.js
> +        <DairyProdLi key={el._id}>
Dairy - молочна продукція
Diary - щоденник

2022-12-25 00:53 UTC, AegisVP commented on src/components/SideBar/SideBar.js
>              <Text>n% of normal</Text>
"n% of normal" - це що? Може "% of total"

2022-12-25 10:20 UTC, Polosmakrr commented on src/components/DiaryForm/Form.js
> +  const params = useParams();
Обробляється, хіба в тебе ні?

2022-12-25 10:21 UTC, Polosmakrr commented on src/components/DiaryForm/Form.js
> +          {allProducts.length !== 0 && showAutocomplete && (
така штука і правда є

2022-12-25 10:21 UTC, Polosmakrr commented on src/components/Calendar/Calendar.js
> +    const dayParam = choseDate.toLocaleDateString().split('.').join('');
Виправлю

2022-12-25 10:22 UTC, Polosmakrr commented on src/components/DiryProductsList/DiryProductsList.js
> +        <DairyProdLi key={el._id}>
То зі старого коду лишилось

2022-12-25 10:22 UTC, Polosmakrr commented on src/components/SideBar/SideBar.js
>              <Text>n% of normal</Text>
так на макеті було

2022-12-25 10:34 UTC, AegisVP commented on src/components/DiaryForm/Form.js
> +  const params = useParams();
Коли я вводив дату в адресній строці, на сторінці дата скидалась до поточної

2022-12-25 10:35 UTC, AegisVP commented on src/components/SideBar/SideBar.js
>              <Text>n% of normal</Text>
Але ж правильно буде "% of total"

2022-12-25 10:35 UTC, AegisVP commented on src/components/DiryProductsList/DiryProductsList.js
> +        <DairyProdLi key={el._id}>
То так і лишаємо?

2022-12-25 13:18 UTC, AegisVP commented on src/components/Calendar/Calendar.js
> +    if (day < 10) {
const day = Date(choseDate.getDate()).padStart(2,'0');
const month = Date(choseDate.getMonth()+1).padStart(2,'0');

2022-12-25 13:34 UTC, Polosmakrr commented on src/components/Calendar/Calendar.js
> +    if (day < 10) {
Виправив

2022-12-25 13:57 UTC, AegisVP requested changes

2022-12-25 13:57 UTC, AegisVP commented on src/components/DiaryForm/Form.js
> +    const date = params.day.split('.').join('');
Ніколи не припускай що дата буде (і будь які данні) в якомусь особливому форматі, якщо ти сам їх не сформував в цьому форматі. Дата може бути розділена '/', місяць може бути після дня (Американський формат)...

2022-12-25 13:57 UTC, AegisVP commented on src/components/Calendar/Calendar.js
> +        let date = params.day.split('.');
як цей код розпарсить дату в такому форматі: "12/31/2022" (31 грудня 2022)?

2022-12-25 13:57 UTC, AegisVP commented on src/components/Calendar/Calendar.js
> +        let date = params.day.split('.');
зроби функцію-парсер дати, бо в тебе цю логику я бичив кілька разів...

2022-12-25 13:57 UTC, AegisVP commented on src/components/Calendar/Calendar.js
> +    let date = value.split('.');
Знову, не можна припускати що дата розділена "."

2022-12-25 13:57 UTC, AegisVP commented on src/components/Calendar/Calendar.js
> +        let date = params.day.split('.');
Я би повертав з неї об'єкт {date,month,year} і всю логіку там запулив...

2022-12-25 15:46 UTC, Polosmakrr commented on src/components/Calendar/Calendar.js
> +    let date = value.split('.');
Так я її сам і встановлю, саме такого формату

2022-12-25 15:47 UTC, Polosmakrr commented on src/components/Calendar/Calendar.js
> +        let date = params.day.split('.');
запросто бо дата буде тільки в такому форматі 21.21.21

2022-12-25 15:47 UTC, Polosmakrr commented on src/components/DiaryForm/Form.js
> +    const date = params.day.split('.').join('');
я не припускаю, а сам створюю її

2022-12-25 22:50 UTC, AegisVP approved these changes

2022-12-25 22:50 UTC, merged