Register form
AegisVP/InSight-web pull request #37
Opened 2022-12-25 12:27 UTC by AnnaKhanina

2022-12-25 16:12 UTC, AegisVP requested changes

2022-12-25 16:12 UTC, AegisVP commented on src/components/InputFormValid/InputEmail.js
> +  <InputForm
autoComplete="username" або autoComplete="email"

2022-12-25 16:12 UTC, AegisVP commented on src/components/InputFormValid/InputName.js
> +  <InputForm
autoComplete="name"

2022-12-25 16:12 UTC, AegisVP commented on src/components/InputFormValid/InputPassword.js
> +  <InputForm
autoComplete="current-password"

2022-12-25 16:12 UTC, AegisVP commented on src/components/LoginForm/LoginForm.jsx
> +    <Login autoComplete="off">
`autocomplete="off"` ставиться саме на форму (в тебе це стилізований div)
Якщо буде автозаповнення, тоді навіть там ставити не треба

2022-12-25 16:12 UTC, AegisVP commented on src/components/LoginForm/LoginForm.styled.jsx
> +
забула `}` щоб закінчити це media правило

2022-12-25 16:12 UTC, AegisVP commented on src/components/RegisterForm/RegisterForm.styled.jsx
> +
забула `}` щоб закінчити це media правило

2022-12-25 16:12 UTC, AegisVP commented on src/components/LoginForm/LoginForm.jsx
> +
Додай кнопку логіна через Гугл
```
        <ButtonReg style={{ margin: 0, marginTop: 20 }}>
          <a href={url}>
            <DefaultButton type="button">Google</DefaultButton>
          </a>
        </ButtonReg>
```

2022-12-25 16:12 UTC, AegisVP commented on src/components/LoginForm/LoginForm.jsx
> +
Додай для логіна через Гугл:
```
  const url = `${constants.apiServerAddress}/user/google`;
```

2022-12-25 16:12 UTC, AegisVP commented on src/components/RegisterForm/RegisterForm.jsx
> +    <Registration autoComplete="off">
`autocomplete="off"` ставиться саме на форму (в тебе це стилізований div)
Якщо буде автозаповнення, тоді навіть там ставити не треба

2022-12-26 09:03 UTC, AnnaKhanina commented on src/components/LoginForm/LoginForm.jsx
> +
+

2022-12-26 11:39 UTC, AegisVP approved these changes

2022-12-26 11:51 UTC, AegisVP approved these changes

2022-12-26 11:52 UTC, merged